# https://docs.travis-ci.com/user/languages/c/

language: c

# sudo: required

addons:
  apt:
    sources:
    - fish-shell/release-2
    packages:
    - fish

    # - sourceline: 'ppa:fish-shell/release-2'

# before_install:
#   - sudo add-apt-repository -y ppa:fish-shell/release-2
#   - sudo apt-get update -q
#   - sudo apt-get install -y fish

install:
  - curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
  - fish -c "fisher fishtape"

script:
  - fish -n **/*.fish # check for syntax issues
  - fish -c "fishtape test/*.test.fish"
