# https://docs.travis-ci.com/user/languages/c/

language: c

sudo: required

addons:
  apt:
    sources:
    - sourceline: 'ppa:fish-shell/release-2'
    packages:
    - fish


install:
  - curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
  - fish -c "fisher fishtape"

script:
  - fish -n **/*.fish # check for syntax issues
  - fish -c "fishtape test/*.test.fish"
